SELECT 
	db1.SEQUENCE_NAME
FROM ecad_bosfor.INFORMATION_SCHEMA.SEQUENCES db1
left join ecad_bosfor_empty.INFORMATION_SCHEMA.SEQUENCES db2 on db2.SEQUENCE_NAME = db1.SEQUENCE_NAME
WHERE db2.SEQUENCE_NAME is null