SELECT 
	db1.TABLE_NAME
FROM ecad_bosfor.INFORMATION_SCHEMA.TABLES db1
left join ecad_bosfor_empty.INFORMATION_SCHEMA.TABLES db2 on db2.TABLE_NAME = db1.TABLE_NAME
WHERE db1.TABLE_TYPE='BASE TABLE' and db2.TABLE_NAME is null